### ISSUE TITLE
Fix ToDo bot - not necessary close

### ISSUE THREAD

**Issue by nesterone** [zorko-io/zorko-platform#167]

**Comment by nesterone** [comment]
after changing events to 
```
on:
  pull_request:
    branches:
      - dev
```

it stoped to generate todos at all
